services:
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "10107:80"
    volumes:
      - minio-data:/data
  postgres-1:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-1-data:/var/lib/postgresql/data

volumes:
  minio-data:
  postgres-1-data:
