services:
  memcached:
    image: memcached:1.6
    restart: unless-stopped
    ports:
      - "10019:80"
  grafana-1:
    image: grafana/grafana:latest
    restart: unless-stopped
  caddy-2:
    image: caddy:2
    restart: unless-stopped
  ubuntu-3:
    image: ubuntu:24.04
    command: sleep infinity
    restart: unless-stopped
  ruby-4:
    image: ruby:3.3-slim
    command: sleep infinity
    restart: unless-stopped
  consul-5:
    image: hashicorp/consul:1.17
    restart: unless-stopped
