services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "10129:80"
  python-1:
    image: python:3.12-slim
    command: sleep infinity
    restart: unless-stopped
  rabbitmq-2:
    image: rabbitmq:3-management
    restart: unless-stopped
  elasticsearch-3:
    image: elasticsearch:8.12.0
    restart: unless-stopped
  busybox-4:
    image: busybox:latest
    command: sleep infinity
    restart: unless-stopped
  debian-5:
    image: debian:bookworm-slim
    command: sleep infinity
    restart: unless-stopped
  php-6:
    image: php:8.3-fpm
    command: sleep infinity
    restart: unless-stopped
