services:
  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    ports:
      - "10109:80"
  alpine-1:
    image: alpine:latest
    command: sleep infinity
    restart: unless-stopped
  golang-2:
    image: golang:1.22
    command: sleep infinity
    restart: unless-stopped
  vault-3:
    image: hashicorp/vault:1.15
    restart: unless-stopped
  nginx-4:
    image: nginx:latest
    restart: unless-stopped
  mysql-5:
    image: mysql:8.0
    restart: unless-stopped
  python-6:
    image: python:3.12-slim
    command: sleep infinity
    restart: unless-stopped
  rabbitmq-7:
    image: rabbitmq:3-management
    restart: unless-stopped
  elasticsearch-8:
    image: elasticsearch:8.12.0
    restart: unless-stopped
  busybox-9:
    image: busybox:latest
    command: sleep infinity
    restart: unless-stopped
  debian-10:
    image: debian:bookworm-slim
    command: sleep infinity
    restart: unless-stopped
  php-11:
    image: php:8.3-fpm
    command: sleep infinity
    restart: unless-stopped
  minio-12:
    image: minio/minio:latest
    restart: unless-stopped
  postgres-13:
    image: postgres:16
    restart: unless-stopped
  node-14:
    image: node:20-alpine
    command: sleep infinity
    restart: unless-stopped
