services:
  httpd:
    image: httpd:2.4
    restart: unless-stopped
    ports:
      - "10176:80"
  mariadb-1:
    image: mariadb:11
    restart: unless-stopped
    volumes:
      - mariadb-1-data:/var/lib/mysql

volumes:
  mariadb-1-data:
