services:
  alpine:
    image: alpine:latest
    command: sleep infinity
    restart: unless-stopped
    ports:
      - "10088:80"
    networks:
      - app-net
  golang-1:
    image: golang:1.22
    command: sleep infinity
    restart: unless-stopped
    networks:
      - app-net
  vault-2:
    image: hashicorp/vault:1.15
    restart: unless-stopped
    networks:
      - app-net
  nginx-3:
    image: nginx:latest
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
