services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "10197:80"
    volumes:
      - mongo-data:/data/db
  httpd-1:
    image: httpd:2.4
    restart: unless-stopped

volumes:
  mongo-data:
