services:
  elasticsearch:
    image: elasticsearch:8.12.0
    restart: unless-stopped
    ports:
      - "10166:80"
  busybox-1:
    image: busybox:latest
    command: sleep infinity
    restart: unless-stopped
