services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "10136:80"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  node-1:
    image: node:20-alpine
    command: sleep infinity
    restart: unless-stopped

volumes:
  postgres-data:
