services:
  elasticsearch:
    image: elasticsearch:8.12.0
    restart: unless-stopped
    ports:
      - "10116:80"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  busybox-1:
    image: busybox:latest
    command: sleep infinity
    restart: unless-stopped

volumes:
  elasticsearch-data:
